package Server;



import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ServerGUI extends javax.swing.JFrame {
    
    Server myServer;

    public ServerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        readerTextArea = new javax.swing.JTextArea();
        senderTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file_menuItem = new javax.swing.JMenu();
        turnOn_menuItem = new javax.swing.JMenuItem();
        turnOff_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        readerTextArea.setEditable(false);
        readerTextArea.setColumns(20);
        readerTextArea.setRows(5);
        jScrollPane1.setViewportView(readerTextArea);

        senderTextField.setToolTipText("write here..");
        senderTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        senderTextField.setName(""); // NOI18N
        senderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderTextFieldActionPerformed(evt);
            }
        });

        sendButton.setText("->");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        file_menuItem.setText("File");
        file_menuItem.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                file_menuItemComponentAdded(evt);
            }
        });

        turnOn_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        turnOn_menuItem.setText("Turn ON");
        turnOn_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOn_menuItemActionPerformed(evt);
            }
        });
        file_menuItem.add(turnOn_menuItem);

        turnOff_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        turnOff_menuItem.setText("Turn OFF");
        turnOff_menuItem.setEnabled(false);
        turnOff_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOff_menuItemActionPerformed(evt);
            }
        });
        file_menuItem.add(turnOff_menuItem);

        menuBar.add(file_menuItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senderTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senderTextField)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderTextFieldActionPerformed

    private void turnOn_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOn_menuItemActionPerformed
        myServer = new Server(this);
        myServer.start();
        turnOn_menuItem.setEnabled(false);
        turnOff_menuItem.setEnabled(true);
        
    }//GEN-LAST:event_turnOn_menuItemActionPerformed

    private void turnOff_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOff_menuItemActionPerformed
        try {
            myServer.shutDown();
        } catch (IOException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        turnOff_menuItem.setEnabled(false);
        turnOn_menuItem.setEnabled(true);
    }//GEN-LAST:event_turnOff_menuItemActionPerformed

    private void file_menuItemComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_file_menuItemComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_file_menuItemComponentAdded

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        myServer.sendBroadcastMessage(senderTextField.getText());
        senderTextField.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu file_menuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextArea readerTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField senderTextField;
    private javax.swing.JMenuItem turnOff_menuItem;
    private javax.swing.JMenuItem turnOn_menuItem;
    // End of variables declaration//GEN-END:variables


    public void setTextArea(String txt){
        readerTextArea.append(txt + System.lineSeparator());
    }
    
    
    

}
